version: "3.8"

services:
  rag-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - fastapi_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
